name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
  ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
  ANDROID_KEY_PASS: ${{ secrets.ANDROID_KEY_PASS }}
  ANDROID_KEYSTORE_PASS: ${{ secrets.ANDROID_KEYSTORE_PASS }}
  WS: ${{ github.workspace }}


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Android:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2      
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          # Version of Visual Studio to search; defaults to latest if not specified
          vs-version: 16.9
      - shell : bash
        run: |
          echo -n "$ANDROID_KEYSTORE" > "$WS\android.keystore.encoded"
          base64 --decode "$WS\android.keystore.encoded" > "$WS\android.keystore"      
      - shell: pwsh
        run: |
          msbuild src/Amusoft.PCR.Mobile.Droid/Amusoft.PCR.Mobile.Droid.csproj /verbosity:minimal /restore /t:"SignAndroidPackage" /bl /p:Configuration=Release /p:OutputPath="$env:WS\artifacts" /p:AndroidKeyStore=true /p:AndroidSigningKeyAlias="$env:ANDROID_KEY_ALIAS" /p:AndroidSigningKeyPass="$env:ANDROID_KEY_PASS" /p:AndroidSigningKeyStore="$env:WS\android.keystore" /p:AndroidSigningStorePass="$env:ANDROID_KEYSTORE_PASS"
          Remove-Item "$env:WS\android.keystore.encoded"
          Remove-Item "$env:WS\android.keystore"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: apk
          path: "**/*-Signed.apk"          
          if-no-files-found: error
          retention-days: 14

          
